dist: xenial
sudo: false
language: python
cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0

matrix:
  exclude:
  # Django 2.0+ doesn't support python 2.7
  - python: 2.7
    env: DJANGO=2.0
  - python: 2.7
    env: DJANGO=2.1
  - python: 2.7
    env: DJANGO=2.2
  - python: 2.7
    env: DJANGO=3.0


  # Django 2.1+ doesn't support python 3.4
  - python: 3.4
    env: DJANGO=2.1
  - python: 3.4
    env: DJANGO=2.2
  - python: 3.4
    env: DJANGO=3.0

  # Django 3.0+ doesn't support python 3.5
  - python: 3.5
    env: DJANGO=3.0

  # Django 1.9+ doesn't support python 3.3
  - python: 3.3
    env: DJANGO=1.9
  - python: 3.3
    env: DJANGO=1.10
  - python: 3.3
    env: DJANGO=1.11
  - python: 3.3
    env: DJANGO=2.0
  - python: 3.3
    env: DJANGO=2.1
  - python: 3.3
    env: DJANGO=2.2
  - python: 3.3
    env: DJANGO=3.0

  # Django 1.7 doesn't support python 3.5+
  - python: 3.5
    env: DJANGO=1.7
  - python: 3.6
    env: DJANGO=1.7
  - python: 3.7
    env: DJANGO=1.7
  - python: 3.8
    env: DJANGO=1.7

  # python 3.6 has deprecated issue with django before 1.11
  # https://stackoverflow.com/questions/41343263/provide-classcell-example-for-python-3-6-metaclass\
  - python: 3.6
    env: DJANGO=1.8
  - python: 3.6
    env: DJANGO=1.9
  - python: 3.6
    env: DJANGO=1.10
  - python: 3.7
    env: DJANGO=1.8
  - python: 3.7
    env: DJANGO=1.9
  - python: 3.7
    env: DJANGO=1.10

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO
  - python setup.py -q install

script:
  python runtests.py

