dist: trusty
sudo: false
language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  exclude:
  # Django 2.0+ doesn't support python 2.7
  - python: 2.7
    env: DJANGO=2.0

  # Django 1.9+ doesn't support python 3.3
  - python: 3.3
    env: DJANGO=1.9
  - python: 3.3
    env: DJANGO=1.10
  - python: 3.3
    env: DJANGO=1.11
  - python: 3.3
    env: DJANGO=2.0

  # Django 1.7 doesn't support python 3.5+
  - python: 3.5
    env: DJANGO=1.7
  - python: 3.6
    env: DJANGO=1.7

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO
  - python setup.py -q install

before_script:
  - psql -tc 'SHOW server_version' -U postgres
  - psql -c 'CREATE ROLE test;' -U postgres
  - psql -c 'ALTER ROLE test WITH SUPERUSER;' -U postgres
  - psql -c 'ALTER ROLE test WITH LOGIN;' -U postgres
  - psql -c "ALTER ROLE test PASSWORD 'test';" -U postgres
  - psql -c 'CREATE DATABASE test OWNER test;' -U postgres
  - psql -c 'CREATE DATABASE test2 OWNER test;' -U postgres

script:
  python runtests.py

